// Copyright © 2010­‐14 MusicGenresList.com

const MusicGenres = {
    Alternative: [
        "Alternative Rock",
        "College Rock",
        "Experimental Rock",
        "Goth Rock",
        "Grunge",
        "Hardcore Punk",
        "Hard Rock",
        "Indie Rock",
        "New Wave",
        "Progressive Rock",
        "Punk",
        "Shoegaze",
        "Steampunk",
    ], Anime: [
    ], Blues: [
        "Acoustic Blues",
        "Chicago Blues",
        "Classic Blues",
        "Contemporary Blues",
        "Country Blues",
        "Delta Blues",
        "Electric Blues",
    ], ChildrensMusic: [
        "Lullabies",
        "Sing-Along",
        "Stories",
    ], Classical: [
        "Avant-Garde",
        "Baroque",
        "Chamber Music",
        "Chant",
        "Choral",
        "Classical Crossover",
        "Early Music",
        "High Classical",
        "Impressionist",
        "Medieval",
        "Minimalism",
        "Modern Composition",
        "Opera",
        "Orchestral",
        "Renaissance",
        "Romantic",
        "Wedding Music",
    ], Comedy: [
        "Novelty",
        "Standup Comedy",
    ], Country: [
        "Alternative Country",
        "Americana",
        "Bluegrass",
        "Contemporary Bluegrass",
        "Contemporary Country",
        "Country Gospel",
        "Honky Tonk",
        "Outlaw Country",
        "Traditional Bluegrass",
        "Traditional Country",
        "Urban Cowboy",
    ], Dance: [
        "Breakbeat",
        "Dubstep",
        "Exercise",
        "Garage",
        "Hardcore",
        "Hard Dance",
        "Hi-NRG / Eurodance",
        "House",
        "Jackin House",
        "Jungle/Drum’n'bass",
        "Techno",
        "Trance",
    ], Disney: [
    ], EasyListening: [
        "Bop",
        "Lounge",
        "Swing",
    ], Electronic: [
        "Ambient",
        "Crunk",
        "Downtempo",
        "Electro",
        "Electronica",
        "Electronic Rock",
        "IDM/Experimental",
        "Industrial",
    ], Enka: [
    ], FrenchPop: [
    ], GermanFolk: [
    ], GermanPop: [
    ], FitnessWorkout: [
    ], HipHopRap: [
        "Alternative Rap",
        "Bounce",
        "Dirty South",
        "East Coast Rap",
        "Gangsta Rap",
        "Hardcore Rap",
        "Hip-Hop",
        "Latin Rap",
        "Old School Rap",
        "Rap",
        "Underground Rap",
        "West Coast Rap",
    ], Holiday: [
        "Chanukah",
        "Christmas",
        "Christmas: Children’s",
        "Christmas: Classic",
        "Christmas: Classical",
        "Christmas: Jazz",
        "Christmas: Modern",
        "Christmas: Pop",
        "Christmas: R&B",
        "Christmas: Religious",
        "Christmas: Rock",
        "Easter",
        "Halloween",
        "Holiday: Other",
        "Thanksgiving",
    ], IndiePop: [
    ], Industrial: [
    ], InspirationalChristianGospel: [
        "CCM",
        "Christian Metal",
        "Christian Pop",
        "Christian Rap",
        "Christian Rock",
        "Classic Christian",
        "Contemporary Gospel",
        "Gospel",
        "Christian & Gospel",
        "Praise & Worship",
        "Qawwali",
        "Southern Gospel",
        "Traditional Gospel",
    ], Instrumental: [
        "March (Marching Band)",
    ], jPop: [
        "J-Rock",
        "J-Synth",
        "J-Ska",
        "J-Punk",
    ], Jazz: [
        "Acid Jazz",
        "Avant-Garde Jazz",
        "Big Band",
        "Blue Note",
        "Contemporary Jazz",
        "Cool",
        "Crossover Jazz",
        "Dixieland",
        "Ethio-jazz",
        "Fusion",
        "Hard Bop",
        "Latin Jazz",
        "Mainstream Jazz",
        "Ragtime",
        "Smooth Jazz",
        "Trad Jazz",
    ], kPop: [
    ], Karaoke: [
    ], Kayokyoku: [
    ], Latino: [
        "Alternativo & Rock Latino",
        "Baladas y Boleros",
        "Brazilian",
        "Contemporary Latin",
        "Latin Jazz",
        "Pop Latino",
        "Raíces",
        "Reggaeton y Hip-Hop",
        "Regional Mexicano",
        "Salsa y Tropical",
    ], NewAge: [
        "Environmental",
        "Healing",
        "Meditation",
        "Nature",
        "Relaxation",
        "Travel",
    ], Opera: [
    ], Pop: [
        "Adult Contemporary",
        "Britpop",
        "Pop/Rock",
        "Soft Rock",
        "Teen Pop",
    ], RnBSoul: [
        "Contemporary R&B",
        "Disco",
        "Doo Wop",
        "Funk",
        "Motown",
        "Neo-Soul",
        "Quiet Storm",
        "Soul",
    ], Reggae: [
        "Dancehall",
        "Dub",
        "Roots Reggae",
        "Ska",
    ], Rock: [
        "Adult Alternative",
        "American Trad Rock",
        "Arena Rock",
        "Blues-Rock",
        "British Invasion",
        "Death Metal/Black Metal",
        "Glam Rock",
        "Hair Metal",
        "Hard Rock",
        "Metal",
        "Metal",
        "Jam Bands",
        "Metal",
        "Prog-Rock/Art Rock",
        "Psychedelic",
        "Rock & Roll",
        "Rockabilly",
        "Roots Rock",
        "Singer/Songwriter",
        "Southern Rock",
        "Surf",
        "Tex-Mex",
    ], SingerSongwriter: [
        "Alternative Folk",
        "Contemporary Folk",
        "Contemporary Singer/Songwriter",
        "Folk-Rock",
        "New Acoustic",
        "Traditional Folk",
    ], Soundtrack: [
        "Foreign Cinema",
        "Musicals",
        "Original Score",
        "Soundtrack",
        "TV Soundtrack",
    ], SpokenWord: [
    ], TexMexTejano: [
        "Chicano",
        "Classic",
        "Conjunto",
        "Conjunto Progressive",
        "New Mex",
        "Tex-Mex",
    ], Vocal: [
        "Barbershop",
        "Doo-wop",
        "Standards",
        "Traditional Pop",
        "Vocal Jazz",
        "Vocal Pop",
    ], World: [
        "Africa",
        "Afro-Beat",
        "Afro-Pop",
        "Asia",
        "Australia",
        "Bossa Nova",
        "Cajun",
        "Caribbean",
        "Celtic",
        "Celtic Folk",
        "Contemporary Celtic",
        "Drinking Songs",
        "Drone",
        "Europe",
        "France",
        "Hawaii",
        "Indian Pop",
        "Japan",
        "Japanese Pop",
        "Klezmer",
        "Middle East",
        "North America",
        "Polka",
        "South Africa",
        "South America",
        "Traditional Celtic",
        "Worldbeat",
        "Zydeco",
    ]
};